name: Daily Build Scheduler

on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:
    inputs:
      model:
        description: Build Model
        required: false
        default: all
        type: choice
        options:
          - all
          - release_wrt
          - x86_wrt

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  trigger-release:
    permissions:
      actions: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trigger Release WRT
        if: inputs.model == 'all' || inputs.model == 'release_wrt' || github.event_name == 'schedule'
        run: |
          gh workflow run release_wrt.yml -f model=jdcloud_ipq60xx_immwrt --repo ${{ github.repository }}

      - name: Trigger X86 WRT
        if: inputs.model == 'all' || inputs.model == 'x86_wrt' || github.event_name == 'schedule'
        run: |
          gh workflow run x86_wrt.yml -f model=x64_immwrt --repo ${{ github.repository }}